export default [
  { source: "USD", cible: "EUR" },
  { source: "EUR", cible: "USD" },
  { source: "USD", cible: "JPY" },
  { source: "EUR", cible: "GBP" },
  { source: "USD", cible: "GBP" },
  { source: "USD", cible: "CAD" },
  { source: "USD", cible: "CHF" },
  { source: "EUR", cible: "CHF" },
  { source: "EUR", cible: "JPY" },
  { source: "GBP", cible: "JPY" },
  { source: "EUR", cible: "INR" },
  { source: "USD", cible: "INR" },
  { source: "USD", cible: "CNY" },
  { source: "EUR", cible: "CNY" },
  { source: "EUR", cible: "AUD" },
  { source: "USD", cible: "AUD" },
  { source: "CAD", cible: "EUR" },
  { source: "CAD", cible: "USD" },
  { source: "USD", cible: "BRL" },
  { source: "EUR", cible: "BRL" },
  { source: "USD", cible: "ZAR" },
  { source: "EUR", cible: "ZAR" },
  { source: "USD", cible: "KRW" },
  { source: "EUR", cible: "KRW" },
  { source: "EUR", cible: "MGA" },
];
