export default [
  { source: "EUR", cible: "USD" },
  { source: "EUR", cible: "GBP" },
  { source: "EUR", cible: "JPY" },
  { source: "EUR", cible: "CHF" },
  { source: "EUR", cible: "CAD" },
  { source: "EUR", cible: "AUD" },
  { source: "EUR", cible: "CNY" },
  { source: "EUR", cible: "INR" },
  { source: "EUR", cible: "MGA" },
  { source: "USD", cible: "EUR" },
  { source: "GBP", cible: "EUR" },
  { source: "JPY", cible: "EUR" },
  { source: "CHF", cible: "EUR" },
  { source: "CAD", cible: "EUR" },
  { source: "AUD", cible: "EUR" },
  { source: "CNY", cible: "EUR" },
  { source: "INR", cible: "EUR" },
  { source: "MGA", cible: "EUR" },
];
